### ISSUE TITLE
server.listeners() is not a function error

### ISSUE THREAD

**Issue by imshubh4141** [laggingreflex/socket.io-encrypt#7]
`[nodemon] restarting due to changes...
[nodemon] starting `node server.js`
C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\engine.io\lib\server.js:454
  var listeners = server.listeners('request').slice(0);
                         ^

TypeError: server.listeners is not a function
    at Server.attach (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\engine.io\lib\server.js:454:26)
    at Function.attach (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\engine.io\lib\engine.io.js:124:10)
    at Server.initEngine (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io\lib\index.js:310:21)
    at C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io\lib\index.js:295:10
    at Encoder.encode (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io-parser\index.js:135:5)
    at Server.listen.Server.attach (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io\lib\index.js:290:16)
    at new Server (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io\lib\index.js:59:17)
    at Server (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\node_modules\socket.io\lib\index.js:44:41)
    at Object.<anonymous> (C:\Users\91790\OneDrive\Desktop\My Chat APP\Node Server\server.js:6:12)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
[nodemon] app crashed - waiting for file changes before starting...`

I get the following error when running my server.js file
The error seems to be in one the node modules file

Can I work on this?
 - should be assigned to someone.

**Comment by laggingreflex** [comment]
Are you sure it's this library? I'm not seeing this library in your stack trace.  

(libraries being `node_modules\engine.io`, `node_modules\socket.io`, ... )

**Comment by imshubh4141** [comment]
Since it points to my node_modules folder, I guess it does point to this library. Also I had installed this package using npm.

**Comment by laggingreflex** [comment]
The error stack trace you shared doesn't seem to contain "socket.io-encrypt" anywhere. If an error originated in this library somewhere it would (most likely) show up in there. Which is why I doubted. If you're sure otherwise please let me know, and how.

**Comment by imshubh4141** [comment]
I get this error only if I have imported this module. I tried using my application after uninstalling in and it works fine
But I'm not sure if the error is being generated in this module.
